# Visit https://www.lddgo.net/en/string/pyc-compile-decompile for more information
# Python 3.8.0 (3413)

from PyQt5 import QtWidgets, QtCore, QtGui

class TaskBar(object):

    def setupUi(self, taskbar):
        self.w = QtWidgets.QDesktopWidget().width()
        self.h = QtWidgets.QDesktopWidget().height()
        taskbar.setGeometry(0, self.h - 50, self.w, 50)
        taskbar.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        taskbar.setStyleSheet("border:1px solid black")
        taskbar.setWindowFlag(QtCore.Qt.WindowStaysOnTopHint)
        self.menu = QtWidgets.QMenu()
        self.menu.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.apps = QtWidgets.QPushButton(taskbar)
        self.apps.setStyleSheet("background-color:rgba(0,0,0,0);border:0.0px solid rgba(0,0,0,100)")
        self.apps.setGeometry(5, 0, 50, 50)
        self.apps.setIconSize(QtCore.QSize(40, 40))
        self.apps.setIcon(QtGui.QIcon("asset/apps.png"))
        self.word = QtWidgets.QPushButton(taskbar)
        self.word.setStyleSheet("background-color:rgba(0,0,0,0);border:0.0px solid rgba(0,0,0,50);border-left:0px solid white")
        self.word.setGeometry(260, 0, 50, 50)
        self.word.setIcon(QtGui.QIcon("asset/word.jpg"))
        self.word.setIconSize(QtCore.QSize(20, 20))
        self.files = QtWidgets.QPushButton(taskbar)
        self.files.setStyleSheet("background-color:rgba(0,0,0,0);border:0.0px solid rgba(0,0,0,50);border-left:0px solid white")
        self.files.setGeometry(290, 0, 50, 50)
        self.files.setIcon(QtGui.QIcon("asset/files.png"))
        self.files.setIconSize(QtCore.QSize(40, 40))
        self.browser = QtWidgets.QPushButton(taskbar)
        self.browser.setGeometry(320, 0, 50, 50)
        self.browser.setStyleSheet("background-color:rgba(0,0,0,0);border:0.0px solid rgba(0,0,0,50);border-left:0px solid white")
        self.browser.setIcon(QtGui.QIcon("asset/browser.png"))
        self.browser.setIconSize(QtCore.QSize(20, 20))
        self.editor = QtWidgets.QPushButton(taskbar)
        self.editor.setGeometry(350, 0, 50, 50)
        self.editor.setStyleSheet("background-color:rgba(0,0,0,0);border:0.0px solid rgba(0,0,0,50);border-left:0px solid white")
        self.editor.setIcon(QtGui.QIcon("asset/editor.png"))
        self.editor.setIconSize(QtCore.QSize(40, 40))
        self.command = QtWidgets.QLineEdit(taskbar)
        self.command.setGeometry(50, 2, 210, 26)
        self.command.setPlaceholderText("Command")
        self.setting = QtWidgets.QPushButton(taskbar)
        self.setting.setGeometry(380, 0, 50, 50)
        self.setting.setStyleSheet("background-color:rgba(0,0,0,0);border:0.0px solid rgba(0,0,0,50);border-left:0px solid white")
        self.setting.setIcon(QtGui.QIcon("asset/setting.png"))
        self.setting.setIconSize(QtCore.QSize(45, 45))
        self.chat = QtWidgets.QPushButton(taskbar)
        self.chat.setGeometry(410, 0, 50, 50)
        self.chat.setStyleSheet("background-color:rgba(0,0,0,0);border:0.0px solid rgba(0,0,0,50);border-left:0px solid white")
        self.chat.setIcon(QtGui.QIcon("asset/chat.png"))
        self.chat.setIconSize(QtCore.QSize(40, 40))

    def app_menu(self):
        self.menu.setStyleSheet("border:1px solid white;background-color:black")
        self.menu.setGeometry(0, self.h - 440, 400, 400)
        self.setup_start(self.menu)
        self.menu.show()

    def setup_start(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 407)
        Form.setStyleSheet("border:1px solid white;background-color:black")
        self.chrome = QtWidgets.QPushButton(Form)
        self.chrome.setGeometry(QtCore.QRect(20, 20, 100, 100))
        self.chrome.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chrome.setAutoFillBackground(False)
        self.chrome.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.chrome.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("asset/browser.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chrome.setIcon(icon)
        self.chrome.setIconSize(QtCore.QSize(75, 75))
        self.chrome.setFlat(True)
        self.chrome.setObjectName("chrome")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(120, 120, 100, 100))
        self.pushButton_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.pushButton_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("asset/word.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 120, 100, 100))
        self.pushButton_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("asset/files.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 20, 100, 100))
        self.pushButton_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_4.setAutoFillBackground(False)
        self.pushButton_4.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.pushButton_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("asset/editor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon3)
        self.pushButton_4.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 220, 100, 100))
        self.pushButton_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_5.setAutoFillBackground(False)
        self.pushButton_5.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("asset/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setText("")
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 120, 100, 100))
        self.pushButton_6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.pushButton_6.setText("")
        self.pushButton_6.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(220, 20, 100, 100))
        self.pushButton_7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_7.setAutoFillBackground(False)
        self.pushButton_7.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.pushButton_7.setText("")
        self.pushButton_7.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 220, 100, 100))
        self.pushButton_8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.pushButton_8.setText("")
        self.pushButton_8.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 220, 100, 100))
        self.pushButton_9.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_9.setAutoFillBackground(False)
        self.pushButton_9.setStyleSheet("background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 0);")
        self.pushButton_9.setText("")
        self.pushButton_9.setIconSize(QtCore.QSize(75, 75))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(20, 320, 501, 81))
        self.pushButton_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButton_10.setAutoFillBackground(False)
        self.pushButton_10.setStyleSheet('background-color: rgb(50, 50, 50);\ncolor: rgba(405, 405, 405, 405);\nfont: 22pt "Segoe UI";')
        self.pushButton_10.setIconSize(QtCore.QSize(501, 81))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setIcon(QtGui.QIcon("asset/exit.jpg"))
        QtCore.QMetaObject.connectSlotsByName(Form)


if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    TaskBar().setupUi()
